#!/usr/bin/env python3
"""
claim_map.py -- every row of CLAIM-SET-FROZEN.md, to a script, to a number.

WHY THIS EXISTS
---------------
On 16 August 2026 the line-by-line pass found that §3.1 asserted H1 at 336/336
while NO script in this repository reproduced hPSC_MEA2's published nae table --
114 of those 336 values, 34% of the paper's first claim, generated by nothing.
The instance was fixed. The general question was not asked: what ELSE is
asserted that no script produces?

This asks it, for all twenty claim rows. It found a second instance immediately:
H3's r = +0.986 came from figure4_replication.py, which only called savefig, so
the number existed nowhere on disk except prose a human had typed.

WHAT EACH STATUS MEANS
----------------------
  TRACED    a script writes an artefact, the artefact holds the number, and the
            draft agrees with the artefact. The only status that is fine.
  PRIMARY   quoted from a published source (the descriptor, a package default).
            No script is expected; the check is that the draft still says it.
  SURVEY    Paper 2 material. Checked against classification_n100_FINAL.csv by
            verify_paper2_claims.py, and checked HERE for presence in paper2/
            rather than draft/. Before 17 Aug these rows were listed but not
            checked anywhere in this file, which meant the map covered Paper 1
            and quietly asserted the rest.
  UNSOURCED asserted in the draft with no artefact behind it. THE BUG CLASS
            THIS SCRIPT EXISTS TO FIND. Exits non-zero.

Usage: python scripts/claim_map.py
Exit 0 = every claim is accounted for.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
DRAFT = ROOT / "draft"
PAPER2 = ROOT / "paper2"
NOTES = ROOT / "notes"

TRACED, PRIMARY, SURVEY = "TRACED", "PRIMARY", "SURVEY"

# ---------------------------------------------------------------------------
# id, status, scripts, artefact, strings that must appear in the artefact,
# strings that must appear in draft/
# ---------------------------------------------------------------------------
CLAIMS = [
    # H1's artefact moved on 19 Aug 2026 with the 336 -> 348 amendment.
    # verify_all.py implements the PRE-amendment convention (NA cells dropped)
    # and its artefact still reports 336/336, 307, 303. That is not stale --
    # it is the cross-check: verify_reproduction_348.py reproduces those exact
    # numbers on the old basis before diverging on the new one, which is what
    # establishes that the two implementations agree. The shipped figures come
    # from the newer script, so the map points at its artefact.
    ("H1", TRACED, ["verify_all.py", "verify_rat_na_cells.py",
                    "verify_reproduction_348.py"], "reproduction_348.txt",
     ["348/348", "319", "314", "hPSC_MEA1", "hPSC_MEA2", "Rat_MEA1"],
     ["348 (100%)", "319", "314"]),

    ("H2", TRACED, ["verify_all.py", "day3_threshold_landscape.py"],
     # AUD-14: these are SUBSTRING tests over the whole artefact. "382" passed
     # here for two weeks while the range minimum was 381, because 382 occurs
     # as an ordinary DIV row value. The floor is 381 on BOTH human plates
     # (hPSC_MEA1 DIV 28 and 48; hPSC_MEA2 DIV 10). A real check would compare
     # the claimed range against min/max of the B5 n@1/min column.
     "verify_all_results.txt", ["B5", "384", "381"],
     ["−0.5%", "384 → 382", ("381–384", "381 to 384")]),

    ("H3", TRACED, ["figure4_replication.py"], "replication_correlation.txt",
     ["+0.986", "+0.289", "321 -> 103", "315 -> 108"],
     ["+0.986", "315 → 108"]),

    ("H4", TRACED, ["verify_all.py"], "verify_all_results.txt",
     ["109.57x"], ["109.6×"]),

    ("S1", SURVEY, ["d3_sample_and_extract.py"], None, [], ["45.1%"]),
    ("S2", SURVEY, ["d3_sample_and_extract.py"], None, [], ["1,429"]),
    ("S3", SURVEY, ["d3_sample_and_extract.py"], None, [], ["5 of"]),
    ("S4", SURVEY, ["d3_sample_and_extract.py"], None, [], ["Five of the 23"]),
    ("S5", PRIMARY, [], None, [],
     # "Neural Metric Tool" (singular) from 23 Aug: it is what Axion's own
     # User Guide and application note call it. G-4.
     ["meaRtools", "MEA-ToolBox", "Neural Metric Tool"]),
    ("S6", SURVEY, ["d3_sample_and_extract.py"], None, [], ["active electrode"]),
    ("S7", SURVEY, ["d3_sample_and_extract.py"], None, [], ["25.5%"]),
    ("S8", SURVEY, ["d3_sample_and_extract.py"], None, [], ["29.4%"]),
    ("P1", SURVEY, ["d3_sample_and_extract.py"], None, [], ["network size"]),

    # Phrase updated 17 Aug. M1 was previously worded "4.5 × the noise standard
    # deviation" and appeared ONLY in §3.6 and §4.2 -- Results and Discussion.
    # It is now stated in §2.1 where it belongs, in the descriptor's own terms,
    # and §4.2 cites it rather than repeating it. The map failing on the
    # rewording is the map working: a claim's phrasing moved and it noticed.
    ("M1", PRIMARY, [], None, [],
     ["4.5 times the estimated noise standard deviation", "rank-matched",
      "no absolute amplitude criterion"]),

    ("M2", TRACED, ["derive_duration.py", "duration_consistency.py"],
     "duration_derivation.txt", ["222", "599.688800000"],
     ["222", "599.689"]),

    ("M3", TRACED, ["ttx_ceiling_two_plates.py"], "ttx_ceiling_two_plates.txt",
     ["9.69", "416", "4/416"], ["9.69", "0.96%"]),

    ("M4", TRACED, ["threshold_suppression.py", "verify_threshold_suppression.py"],
     "threshold_suppression.txt",
     ["flagged electrode-recordings   91", "in the bottom decile           76"],
     ["36 (77%)", "40 (91%)", "76 (84%)"]),

    ("A1", TRACED, ["bound_inactive.py"], "inactive_bound.txt",
     ["0.39%"], ["0.39%"]),

    ("A2", TRACED, ["verify_all.py", "threshold_suppression.py"],
     "threshold_suppression.txt", ["45", "51", "56", "59"],
     ["143", "69", "45", "133"]),

    ("A2b", TRACED, ["threshold_suppression.py", "verify_threshold_suppression.py"],
     "threshold_suppression.txt",
     ["ratio to DIV 45 at each percentile"],
     ["0 of 384", "DIV 42 onward"]),
]

fails, warns = [], []


def draft_text(d=None):
    out = []
    for p in sorted((d or DRAFT).glob("*.md")):
        t = p.read_text(encoding="utf-8")
        cut = re.search(r"^#{2,4}\s*.*(drafting notes|notes on this draft|"
                        r"remove before submission)", t, re.M | re.I)
        out.append(t[:cut.start()] if cut else t)
    return re.sub(r"\s+", " ", "\n".join(out))


def main():
    body = draft_text()
    body2 = draft_text(PAPER2) if PAPER2.exists() else ""
    print("claim -> script -> number     (CLAIM-SET-FROZEN.md, all rows)")
    print("=" * 78)
    print(f"{'claim':<6}{'status':<10}{'artefact':<34}{'result'}")
    print("-" * 78)

    for cid, status, scripts, art, in_art, in_draft in CLAIMS:
        problems = []

        for s in scripts:
            if not (ROOT / "scripts" / s).exists():
                problems.append(f"script missing: {s}")

        if status == TRACED:
            if not art:
                problems.append("TRACED but no artefact named")
            else:
                p = NOTES / art
                if not p.exists():
                    problems.append(f"artefact absent: notes/{art}")
                else:
                    txt = p.read_text(encoding="utf-8", errors="replace")
                    for frag in in_art:
                        if frag not in txt:
                            problems.append(f"not in notes/{art}: {frag!r}")

        # SURVEY rows must appear in paper2/; everything else in draft/
        target, tname = ((body2, "paper2/") if status == SURVEY
                         else (body, "draft/"))
        # 28 Aug 2026: a fragment may be a TUPLE of alternative renderings, any
        # one of which satisfies it. Added because the register pass replaced the
        # en dash in "381-384" with the word "to", which broke this row while the
        # claim itself was untouched. A substring test that pins typography fails
        # on a wording decision and reports it as a missing claim, which is the
        # loudest possible false alarm. Alternatives are spelled out here rather
        # than matched loosely, so the set of accepted renderings stays visible.
        for frag in in_draft:
            alts = frag if isinstance(frag, tuple) else (frag,)
            if not any(a in target for a in alts):
                problems.append(f"not in {tname}: {frag!r}")

        shown = f"notes/{art}" if art else "—"
        if problems:
            print(f"{cid:<6}{'UNSOURCED':<10}{shown:<34}FAIL")
            for pr in problems:
                print(f"{'':<50}{pr}")
                fails.append(f"{cid}: {pr}")
        else:
            print(f"{cid:<6}{status:<10}{shown:<34}ok")

    print("-" * 78)

    # Any claim row in the frozen set that this map does not mention at all is
    # the same failure one level up: an unwatched claim.
    known = {c[0] for c in CLAIMS}
    src = (NOTES / "CLAIM-SET-FROZEN.md").read_text(encoding="utf-8")
    declared = set(re.findall(r"^\*\*([HSMAP]\d+[a-z]?)\.", src, re.M))
    missed = sorted(declared - known)
    extra = sorted(known - declared)
    if missed:
        print(f"  CLAIM ROWS NOT IN THIS MAP: {', '.join(missed)}")
        fails.append(f"claim rows absent from the map: {missed}")
    else:
        print(f"  every one of the {len(declared)} rows in "
              f"CLAIM-SET-FROZEN.md is mapped")
    if extra:
        print(f"  mapped but no longer in the claim set: {', '.join(extra)}")
        warns.append(f"stale map entries: {extra}")

    print("=" * 78)
    n_traced = sum(1 for c in CLAIMS if c[1] == TRACED)
    print(f"{n_traced} traced to a script and an artefact, "
          f"{sum(1 for c in CLAIMS if c[1] == PRIMARY)} primary-source, "
          f"{sum(1 for c in CLAIMS if c[1] == SURVEY)} survey (Paper 2)")
    print(f"{len(fails)} failure(s), {len(warns)} warning(s)")
    for f in fails:
        print(f"  - {f}")
    for w in warns:
        print(f"  ~ {w}")
    print("=" * 78)
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
